const categorias = ["Hamburguesas", "Lomos", "Pizzas", "Papas Fritas", "Bebidas"];

const productos = [
  {
    id: 1,
    nombre: "Hamburguesa Triple",
    descripcion: "Hamburguesa triple smash con mucho cheddar.",
    precio: 25000,
    imagen: "./assets/hamburguesa.png",
    categoria: "Hamburguesas",
  },
  {
    id: 2,
    nombre: "Hamburguesa Doble",
    descripcion: "Doble medallón de carne con queso y salsa especial.",
    precio: 19000,
    imagen: "./assets/hamburguesa.png",
    categoria: "Hamburguesas",
  },
  {
    id: 3,
    nombre: "Lomito Completo",
    descripcion: "Lomito con jamón, queso, lechuga, tomate y huevo.",
    precio: 22000,
    imagen: "https://placehold.co/200x200/8B4513/white?text=Lomito+Completo",
    categoria: "Lomos",
  },
  {
    id: 4,
    nombre: "Lomito Especial",
    descripcion: "Lomito con bacon, cheddar fundido y cebolla caramelizada.",
    precio: 26000,
    imagen: "https://placehold.co/200x200/8B4513/white?text=Lomito+Especial",
    categoria: "Lomos",
  },
  {
    id: 5,
    nombre: "Pizza Muzzarella",
    descripcion: "Salsa de tomate casera y muzzarella abundante.",
    precio: 18000,
    imagen: "./assets/pizza.png",
    categoria: "Pizzas",
  },
  {
    id: 6,
    nombre: "Pizza Napolitana",
    descripcion: "Muzzarella, rodajas de tomate, ajo y aceitunas verdes.",
    precio: 20000,
    imagen: "./assets/pizza.png",
    categoria: "Pizzas",
  },
  {
    id: 7,
    nombre: "Papas con Cheddar",
    descripcion: "Papas fritas crocantes con cheddar derretido y bacon.",
    precio: 8000,
    imagen: "./assets/papas.png",
    categoria: "Papas Fritas",
  },
  {
    id: 8,
    nombre: "Papas con Bacon",
    descripcion: "Papas fritas con bacon crocante y salsa barbacoa.",
    precio: 9500,
    imagen: "./assets/papas.png",
    categoria: "Papas Fritas",
  },
  {
    id: 9,
    nombre: "Gaseosa Cola 500ml",
    descripcion: "Bebida gaseosa sabor cola, botella de 500ml.",
    precio: 3500,
    imagen: "https://placehold.co/200x200/2A9D8F/white?text=Gaseosa+Cola",
    categoria: "Bebidas",
  },
  {
    id: 10,
    nombre: "Agua Mineral 500ml",
    descripcion: "Agua mineral sin gas, botella de 500ml.",
    precio: 2000,
    imagen: "https://placehold.co/200x200/2A9D8F/white?text=Agua+Mineral",
    categoria: "Bebidas",
  },
];
